Remove trivialVersions arg from controller-gen command
To fix the following:
Error: unable to parse option "crd:trivialVersions=true,crdVersions=v1":
[unknown argument "trivialVersions" (at <input>:1:16)
 extra arguments provided: "true,crdVersions=v1" (at <input>:1:17)]

Signed-off-by: Hasan Turken <turkenh@gmail.com>
(cherry picked from commit b431bde5fd11a6c9e376325039c96e20814ef860)